<?xml version="1.0" encoding="utf-8"?>
<Database Name="KG-IMS" EntityNamespace="KG_IMS.DAL" ContextNamespace="KG_IMS.DAL" Class="KG_IMS" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.OPS_T_Category" Member="OPS_T_Category">
    <Type Name="OPS_T_Category">
      <Column Name="CategoryGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EquipTypeGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="OPS_T_Category_FK00" Member="OPS_T_EquipTypes" ThisKey="EquipTypeGUID" OtherKey="EquipTypeGUID" Type="OPS_T_EquipTypes" IsForeignKey="true" />
      <Association Name="OPS_T_Equipment_FK00" Member="OPS_T_Equipment" ThisKey="CategoryGUID" OtherKey="CategoryGUID" Type="OPS_T_Equipment" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.OPS_T_Equipment" Member="OPS_T_Equipment">
    <Type Name="OPS_T_Equipment">
      <Column Name="EquipGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KGID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CategoryGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LocationGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SerialNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Supplier" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PurchasePrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Certificate" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InService" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EquipTypeGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="OPS_T_Equipment_FK00" Member="OPS_T_Category" ThisKey="CategoryGUID" OtherKey="CategoryGUID" Type="OPS_T_Category" IsForeignKey="true" />
      <Association Name="OPS_T_Equipment_FK01" Member="OPS_T_EquipTypes" ThisKey="EquipTypeGUID" OtherKey="EquipTypeGUID" Type="OPS_T_EquipTypes" IsForeignKey="true" />
      <Association Name="OPS_T_Equipment_FK02" Member="S_Locations" ThisKey="LocationGUID" OtherKey="LocationGUID" Type="S_Locations" IsForeignKey="true" />
      <Association Name="OPS_T_Equipment_Service_FK00" Member="OPS_T_Equipment_Service" ThisKey="EquipGUID" OtherKey="EquipGUID" Type="OPS_T_Equipment_Service" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.OPS_T_Equipment_Service" Member="OPS_T_Equipment_Service">
    <Type Name="OPS_T_Equipment_Service">
      <Column Name="ServiceGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EquipGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ServiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SeviceName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tagged" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="OPS_T_Equipment_Service_FK00" Member="OPS_T_Equipment" ThisKey="EquipGUID" OtherKey="EquipGUID" Type="OPS_T_Equipment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OPS_T_EquipTypes" Member="OPS_T_EquipTypes">
    <Type Name="OPS_T_EquipTypes">
      <Column Name="EquipTypeGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="OPS_T_Category_FK00" Member="OPS_T_Category" ThisKey="EquipTypeGUID" OtherKey="EquipTypeGUID" Type="OPS_T_Category" DeleteRule="NO ACTION" />
      <Association Name="OPS_T_Equipment_FK01" Member="OPS_T_Equipment" ThisKey="EquipTypeGUID" OtherKey="EquipTypeGUID" Type="OPS_T_Equipment" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.OPS_T_UserSecurity" Member="OPS_T_UserSecurity">
    <Type Name="OPS_T_UserSecurity">
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SecurityLevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.s_Locations" Member="S_Locations">
    <Type Name="S_Locations">
      <Column Name="LocationGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="OPS_T_Equipment_FK02" Member="OPS_T_Equipment" ThisKey="LocationGUID" OtherKey="LocationGUID" Type="OPS_T_Equipment" DeleteRule="NO ACTION" />
      <Association Name="s_Projects_FK00" Member="S_Projects" ThisKey="LocationGUID" OtherKey="LocationGUID" Type="S_Projects" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.s_NameValue" Member="S_NameValue">
    <Type Name="S_NameValue">
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.s_People" Member="S_People">
    <Type Name="S_People">
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GivenName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Workphone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Homephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GenderClassGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EmploymentClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrganisationGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OnsiteContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OffsiteContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CommencedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CeasedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SupervisorGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="NextofKin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NextofKinPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StaffContractor" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PhotoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MineHealthNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.s_Projects" Member="S_Projects">
    <Type Name="S_Projects">
      <Column Name="ProjGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Client" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ClientProject" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LocationGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDatePlanned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateActual" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="s_Projects_FK00" Member="S_Locations" ThisKey="LocationGUID" OtherKey="LocationGUID" Type="S_Locations" IsForeignKey="true" />
      <Association Name="s_WBS_FK00" Member="S_WBS" ThisKey="ProjGUID" OtherKey="ProjGUID" Type="S_WBS" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.s_SecurityLevels" Member="S_SecurityLevels">
    <Type Name="S_SecurityLevels">
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SecurityLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.s_WBS" Member="S_WBS">
    <Type Name="S_WBS">
      <Column Name="WBSGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="s_WBS_FK00" Member="S_Projects" ThisKey="ProjGUID" OtherKey="ProjGUID" Type="S_Projects" IsForeignKey="true" />
    </Type>
  </Table>
</Database>